// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2vS3auubGzS2LcYIhLFX0gKk33xvSV8Y',
    appId: '1:677191252450:web:a6466cbe3dd3eb75f4a1bb',
    messagingSenderId: '677191252450',
    projectId: 'teamup-c302c',
    authDomain: 'teamup-c302c.firebaseapp.com',
    storageBucket: 'teamup-c302c.firebasestorage.app',
    measurementId: 'G-T63PQVQ26Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-XiA4BTf2wmqIlwWOVTUagkYI4l9oCDU',
    appId: '1:677191252450:android:7e67bbdd15bef646f4a1bb',
    messagingSenderId: '677191252450',
    projectId: 'teamup-c302c',
    storageBucket: 'teamup-c302c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4-TDkESi5iC4fnVYQEzTCWuUhe_bFhqQ',
    appId: '1:677191252450:ios:0737f478d12eb7e3f4a1bb',
    messagingSenderId: '677191252450',
    projectId: 'teamup-c302c',
    storageBucket: 'teamup-c302c.firebasestorage.app',
    androidClientId: '677191252450-plq6hd0tkmh0befgpm2lrh06hpf7mj37.apps.googleusercontent.com',
    iosBundleId: 'ru.ballisty.teamup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4-TDkESi5iC4fnVYQEzTCWuUhe_bFhqQ',
    appId: '1:677191252450:ios:0737f478d12eb7e3f4a1bb',
    messagingSenderId: '677191252450',
    projectId: 'teamup-c302c',
    storageBucket: 'teamup-c302c.firebasestorage.app',
    androidClientId: '677191252450-plq6hd0tkmh0befgpm2lrh06hpf7mj37.apps.googleusercontent.com',
    iosBundleId: 'ru.ballisty.teamup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2vS3auubGzS2LcYIhLFX0gKk33xvSV8Y',
    appId: '1:677191252450:web:b2bc2ffe1199a264f4a1bb',
    messagingSenderId: '677191252450',
    projectId: 'teamup-c302c',
    authDomain: 'teamup-c302c.firebaseapp.com',
    storageBucket: 'teamup-c302c.firebasestorage.app',
    measurementId: 'G-ZQRVLC7J6X',
  );

}